name: CineScreen
options:
  bundleIdPrefix: com.cinescreen
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  groupSortPosition: top
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "2.3.0"
    CURRENT_PROJECT_VERSION: "1"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_STYLE: Manual
    DEVELOPMENT_TEAM: JAT3GYBPJ4
    ARCHS: "$(ARCHS_STANDARD)"
    ONLY_ACTIVE_ARCH: NO
    ENABLE_USER_SCRIPT_SANDBOXING: YES
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      GCC_OPTIMIZATION_LEVEL: "0"
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      SWIFT_COMPILATION_MODE: wholemodule
      GCC_OPTIMIZATION_LEVEL: "s"

targets:
  CineScreen:
    type: application
    platform: macOS
    sources:
      - path: CineScreen
        excludes:
          - "Info.plist"
          - "CineScreen.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cinescreen.app.native
        PRODUCT_NAME: CineScreen
        INFOPLIST_FILE: CineScreen/Info.plist
        CODE_SIGN_ENTITLEMENTS: CineScreen/CineScreen.entitlements
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
        Release:
          CODE_SIGN_IDENTITY: "Developer ID Application"
